# Generated by Django 2.2.7 on 2019-11-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_ad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo_ad', models.CharField(max_length=200, verbose_name='nombre_completo_ad')),
                ('nombre_usuario_ad', models.CharField(max_length=220, verbose_name='nombre_usuario_ad')),
                ('Estado_actual', models.CharField(max_length=220, verbose_name='Estado_actual')),
                ('contrasena_ad', models.CharField(max_length=220, verbose_name='contrasena_ad')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_eq', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=200, verbose_name='nombre_equipo')),
                ('pokemon_1', models.CharField(max_length=200, verbose_name='pokemon_1')),
                ('pokemon_2', models.CharField(max_length=200, verbose_name='pokemon_2')),
                ('pokemon_3', models.CharField(max_length=200, verbose_name='pokemon_3')),
                ('pokemon_4', models.CharField(max_length=200, verbose_name='pokemon_4')),
                ('pokemon_5', models.CharField(max_length=200, verbose_name='pokemon_5')),
                ('pokemon_6', models.CharField(max_length=200, verbose_name='pokemon_6')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_us', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo_us', models.CharField(max_length=200, verbose_name='nombre_completo_us')),
                ('nombre_usuario_us', models.CharField(max_length=200, verbose_name='nombre_usuario_us')),
                ('contrasena_us', models.CharField(max_length=220, verbose_name='contrasena_us')),
            ],
        ),
    ]
